### ISSUE TITLE
Add Voltex FW mode

### ISSUE THREAD

**Issue by HWXLR8** [HWXLR8/beef-board#18]
Been doing some thinking about this one, and it looks like we are going to need a special FW mode for voltex. There are a couple of hurdles:

1. The [encoders used in cryto's voltex controller](https://www.sensatec.co.jp/e/products/catalog.php/293/ST-ELV-24X35B-K_EN.pdf]) use a single 3 pin connector with a variable voltage output. Our design was made with the assumption that controllers will always use encoders with 2 data lines (either in a 2x 3pin format or combined in a single 4pin). As this is not the case, we can re-use one of the 3-pin encoder inputs as an input for these voltex encoders, but we will have to change how the input is handled in FW.
2. The lighting effects run down the sides on the SVRE9, which would also need special FW. Not even sure what type of LEDs this thing uses, but I will experiment and find out.

For now I think it is acceptable to have this a compile-time flag, eventually I would like this to be toggled using a button combo.

Assigning this to myself for now, @supervaka feel free to chime in with your thoughts

**Comment by HWXLR8** [comment]
Support for sensatec encoders has been added in V6. We can keep this issue on hold until you have a board in your hands to try out.

**Comment by ASleepyCat** [comment]
> Support for sensatec encoders has been added in V6. @ASleepyCat We can keep this issue on hold until you have a board in your hands to try out.

Since I only have an SVSE5, I won't be able to help on RGB LED stuff with the SVRE9 and FAUCETWO.

**Comment by HWXLR8** [comment]
> Since I only have an SVSE5, I won't be able to help on RGB LED stuff with the SVRE9 and FAUCETWO.

No problem, LED support is low priority. I will eventually get my hands on a FAUCETWO
