### ISSUE TITLE
Set up guide?

### ISSUE THREAD

**Issue by ASleepyCat** [HWXLR8/beef-board#21]
Wiring up the buttons is straightforward and work fine, but the turntable is unresponsive (both in spicecfg and in Windows' controller testing tool) when connecting both photo interrupter cables to `DAO_E1P1` and `DAO_E2P1` . If I connect the second cable to `DAO_E1P2`, it causes spicetools to crash when setting up the analog controls. The turntable and centre bar LEDs also don't turn on when their cables are connected to `TT_LED` and `DAO_BAR` (centre bar lighting isn't implemented so that's understandable).

I'm probably doing something wrong, so could you detail which cables connects where?

**Comment by ASleepyCat** [comment]
I changed back to the stock board and everything works fine there, so it's an issue with my board,

**Comment by ASleepyCat** [comment]
Nevermind, for some reason I confused the TT headers and everything works now.

**Comment by HWXLR8** [comment]
PM'd on sows
