### ISSUE TITLE
B8-B11 not fully supported by INFINITAS

### ISSUE THREAD

**Issue by Mechada2dx** [HWXLR8/beef-board#42]
I've been testing INFINITAS with beef-board and from what I can see the game only reads from B9 to B12 respectively for start button and stuff. I can see this still working fine for a 2 button controller since you can just plug in B9 and B10, but for PWAN/RED (4 button controllers overall) this could become an issue specially for a RED since you need 2 PCBs.

**Comment by HWXLR8** [comment]
@ASleepyCat / @supervaka I have confirmed on my end that B8 is unresponsive on infinitas. What do you say we kill B8 and just map B1-B7 then B9-B12?
