### ISSUE TITLE
Add support for second rotary encoder

### ISSUE THREAD

**Issue by HWXLR8** [HWXLR8/beef-board#75]
SDVX can use two types of encoders, photointerrupters (same mechanism as IIDX TT), and the sensatecs which act as analog potentiometers. This issue is only for the photointerrupter type encoder.

**Comment by ASleepyCat** [comment]
How about copals?

**Comment by HWXLR8** [comment]
You referring to these guys?
![image](https://github.com/HWXLR8/beef-board/assets/24576775/0192d353-6479-4caf-91b5-b6b50fb42c05)
If so, then I have no plans to support these for now. I can't imagine anyone building a controller would opt to use these instead of something more "pleasant".
