### ISSUE TITLE
Half of RGB Turntable white 

### ISSUE THREAD

**Issue by Mechada2dx** [HWXLR8/beef-board#83]
from what I've been told beefboard reads 15 LEDs for RGB?, here I'm using 45 LED rings so it makes half of the turntable be a white color instead of the desired RGB mode.

![20240624_125136](https://github.com/HWXLR8/beef-board/assets/153807287/7156a293-ed88-40f4-88fe-4f7679d89489)

**Comment by ASleepyCat** [comment]
Yeah the firmware assumes there's 16 LEDs in the turntable lights. I could expose that in the makefile so that people can adjust it for their own setups.

**Comment by HWXLR8** [comment]
Agree with the makefile implementation
